### PR TITLE
HC-435: Upgrade Elasticsearch 7.9 -> 7.10

### PR DESCRIPTION
**Pull request by DustinKLo**
related ticket(s):
- https://hysds-core.atlassian.net/browse/HC-435
- https://jira.jpl.nasa.gov/browse/NSDS-2302

related PR(s):
- https://github.com/hysds/hysds/pull/146

change(s):
- the `query` method will use the PIT + `search_after` API when using es >=7.10, scroll API if <7.10
- bump version

### CODE REVIEW

**Review by pymonger — APPROVED** [review]
Looks good. Let's get @mcayanan to check this out as well in case I missed something.

**Comment by mcayanan** [comment]
@pymonger Let me run through a few SWOT force branches as a sanity check first

**Review by mcayanan — APPROVED** [review]
I ran through the SWOT force branches and they look good as-is with these changes. So feel free to merge

**Comment by pymonger** [comment]
LGTM. Feel free to merge in.

**Pull request merged**
