### PR TITLE
Hc 279 Remove deprecated HySDS code

### PR DESCRIPTION
**Pull request by DustinKLo**
https://hysds-core.atlassian.net/browse/HC-279

### CODE REVIEW

**Review by mcayanan — CHANGES_REQUESTED** [review]
request_utils.py looks like its deleted, but we're still using it in pcm_commons:

https://github.jpl.nasa.gov/IEMS-SDS/pcm_commons/blob/develop/pcm_commons/deploy/cluster_utils.py

Feel free to update pcm_commons to whatever is used in place of this. If you can, please test the changes using the procedures documented in the PCM Operator Guide as the tool that uses this is not part of the smoke test: https://docs.google.com/document/d/1tTCVC8SteoLf1CSYK37GMvL8rZP7HoawKeAli04Ut00/edit#heading=h.5k4cw48b123m

**Review by pymonger — APPROVED** [review]

**Comment by pymonger** [comment]
thanks for catching that @mcayanan.

**Comment by DustinKLo** [comment]
@mcayanan good catch, that would break out E2E tests

**Comment by DustinKLo** [comment]
@mcayanan ran the `deploy_pges` script with the changes to  `pcm_commons`
https://github.jpl.nasa.gov/IEMS-SDS/pcm_commons/pull/8#issuecomment-332354

also checked `swot-pcm` and `swot-chimera` and theyre not using any of the code i removed from `hysds_commons`

**Review by mcayanan — APPROVED** [review]

**Pull request merged**
